print("Soy homero chino")
print("homero")
print("homero chino")
print("homero")
print("homero chino")
print("homero")
print("homero chino")
print("homero")
print("homero chino")
print("homero")
print("homero chino")